name: FocusBuddy
options:
  bundleIdPrefix: com.focusbuddy
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    ENABLE_HARDENED_RUNTIME: YES
    CODE_SIGN_IDENTITY: "-"

targets:
  FocusBuddy:
    type: application
    platform: macOS
    sources:
      - path: FocusBuddy
        excludes:
          - "**/*.xcassets"
      - path: FocusBuddy/Resources/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.focusbuddy.app
        INFOPLIST_FILE: FocusBuddy/Info.plist
        PRODUCT_NAME: FocusBuddy
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES
        LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - "@executable_path/../Frameworks"
    info:
      path: FocusBuddy/Info.plist
      properties:
        CFBundleName: FocusBuddy
        CFBundleDisplayName: FocusBuddy
        CFBundleIdentifier: com.focusbuddy.app
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
        CFBundlePackageType: APPL
        CFBundleExecutable: FocusBuddy
        LSMinimumSystemVersion: "14.0"
        LSUIElement: true
        NSHighResolutionCapable: true
        NSHumanReadableCopyright: "Copyright © 2026 Hiro. All rights reserved."
